### PR TITLE
Add release process description to README.

### PR DESCRIPTION
**Pull request by BigBlueHat**
Figured we should document this so others can follow it in future (and improve on it eventually).

### CODE REVIEW

**Review by iherman — APPROVED** [review]
Don't we need something about how to publish on `cdn.jsdelivr.net`?

**Comment by davidlehn** [comment]
The pattern presented here is problematic.  It is storing large built files in git history forever.  This will continue to grow bloat in the source repo that is otherwise small.  I suggest using a npm process.
https://github.com/w3c/respec-vc/issues/4

I have access to publish packages now.  Including build artifacts in the packages uploaded to npm and omitting them from source control is a common best practice.  The only user difference will be a slightly different CDN URL.  I think the only main issue here is it would be good to have a backup person or two with access to publish the package.

**Comment by iherman** [comment]
@deniak, can I be added on the list for npm publishing? @davidlehn, if that is good, then I can be a fall back, see https://github.com/w3c/respec-vc/pull/37#issuecomment-2216400553.

@deniak, how does that work exactly. I do submit packages to npm time-to-time, but from my own repositories. Will npm just "know"?

**Comment by iherman** [comment]
Just asked @deniak for an account, @davidlehn.

**Review by thereisnogabe — APPROVED** [review]

**Comment by BigBlueHat** [comment]
Merged this as (despite it's less than ideal nature) this is how we do it today...so it merits documentation. We can look to #4 or other for future improvement.

**Pull request merged**
