### PR TITLE
Add addContext function

### LINKED ISSUE #2: Failed to attach proof if custom @context included
When "https://imsglobal.github.io/openbadges-specification/context.json" is included in the list of contexts, the proof cannot be generated. The error is:

> Failed to attach proof to Verifiable Credential. jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.

The URL is public (no CORS) and does return JSON. Do I need a custom documentLoader?

This works,

```
          {
            "@context": [
              "https://www.w3.org/2018/credentials/v1",
              "https://www.w3.org/2018/credentials/examples/v1"
            ],
            "id": "http://example.edu/credentials/3732",
            "type": ["VerifiableCredential", "OpenBadge"],
            "issuer": {
              "id": "https://example.edu/issuers/565049",
              "type": "IssuerProfile",
              "name": "Example University"
            },
            "issuanceDate": "2010-01-01T00:00:00Z",
            "credentialSubject": {
              "id": "did:example:ebfeb1f712ebc6f1c276e12ec21"
            }
          }
```

But this does not,

```
          {
            "@context": [
              "https://www.w3.org/2018/credentials/v1",
              "https://www.w3.org/2018/credentials/examples/v1",
              "https://imsglobal.github.io/openbadges-specification/context.json"
            ],
            "id": "http://example.edu/credentials/3732",
            "type": ["VerifiableCredential", "OpenBadge"],
            "issuer": {
              "id": "https://example.edu/issuers/565049",
              "type": "IssuerProfile",
              "name": "Example University"
            },
            "issuanceDate": "2010-01-01T00:00:00Z",
            "credentialSubject": {
              "id": "did:example:ebfeb1f712ebc6f1c276e12ec21"
            }
          }
```

### PR DESCRIPTION
**Pull request by amiller-ims**
Fixes #2 

Adds and exports an addContext function that authors can use to cache their own context. For example,

```html
    <script class="remove" src="https://cdn.jsdelivr.net/gh/digitalbazaar/respec-vc@1.0.0/dist/main.js"></script>
    <script>
      const url = "https://imsglobal.github.io/openbadges-specification/context.json";
      fetch(url)
      .then(res => res.json())
      .then(context => window.respecVc.addContext(url, context));
    </script>
```

### CODE REVIEW

**Review by kdenhartog — APPROVED** [review]
Great idea - this should be quite useful!

**Comment by davidlehn** [comment]
Two related issues here.

I'm not sure what the sequencing of this will be.  In the vc-data-model spec the `createVcExamples` call happens in a `postProcess` hook.  If the "Retrieve obContext" part here is async, will the `postProcess` hook be run too early?  Seems like a race condition in that case?  A static context would work of course.

Setting things up in this way is just showing that we need to do work on making documentLoaders easier to use.  The right way to do this is probably that you would append your own caching async documentLoader (probably from a helper library for such things).  It could then load your custom contexts in whatever way is needed.  So `createVcExamples` would just be using the existing machinery to load static or dynamic contexts on demand.

The `extendContextLoader` style used here, along with a local mapping lookup, and then adding API calls into that... is kind of odd.  But maybe best to just use this patch until that can all be fixed in a more global way.

**Comment by amiller-ims** [comment]
> The `extendContextLoader` style used here, along with a local mapping lookup, and then adding API calls into that... is kind of odd. But maybe best to just use this patch until that can all be fixed in a more global way.

I agree. When Manu announced respec-vc I sensed a desire to release the simplest possible thing that works. That's the approach I took here. It does put the onus on implementers to avoid race conditions and handle errors.

**Comment by amiller-ims** [comment]
Updated the example to show fetching the context.

**Comment by davidlehn** [comment]
@amiller-ims Please remove `package-lock.json` from that last commit.

**Comment by davidlehn** [comment]
Did you mean to revert the whole commit?
Also I meant use rebase, or other means, to squash package-lock out of the commit history.  (otherwise it stays around forever)

**Comment by amiller-ims** [comment]
I did mean to revert the whole commit. The change to index.html was only for my testing. I was rushing and did not think it through.

Is it OK that the commit (and revert) are in the history? I have only ever used rebase and squash when teaching myself git. I'm afraid I would make things worse if I fumbled through them now.

**Comment by davidlehn** [comment]
@amiller-ims It's nice to have clean commit histories in PRs when merging.  Otherwise unneeded commits end up in history forever.  In this case, I think you could just drop that merge commit and the one that added and reverted things?  It's a good skill to learn.  I use `git rebase -i ...` all the time.  And also it's only 6 lines in the PR, so not hard to fix if mistakes are made. ;-)  The alternative is we can squash when merging if needed, but it's easy to forget to do that.

**Comment by amiller-ims** [comment]
I'll give it a try. Thank you for the encouragement.

**Comment by amiller-ims** [comment]
@davidlehn I think it worked and I learned something. Thank you!

**Review by msporny — APPROVED** [review]

**Pull request merged**
