### PR TITLE
Add rendering for VC-JOSE-COSE

### LINKED ISSUE #9: Incorporate VC-JOSE-COSE
Related to https://github.com/w3c/vc-jose-cose/issues/214, without support for [VC-JOSE-COSE](https://github.com/w3c/vc-jose-cose) (specifically SD-JWT in this case) it will be difficult to render examples for published VC-JOSE-COSE specs as a part of the W3C process.

It looks like there is already work done here https://github.com/transmute-industries/respec-vc-jwt which could be incorporated into this repo. Unfortunately my JS skills are limited so I am hesitant to open a change request myself.

Is there a maintainer of the project I can work with to see this through?

### PR DESCRIPTION
**Pull request by thereisnogabe**
Fix #9 

Migrated code from https://github.com/w3c/vc-jose-cose/tree/main/plugin here

Had to massage polyfills. Updated the README and examples. Looks good on my screen!

Note: the code works off a static P-384 key. We can adjust this to use the same key across all examples, but I figure this is a decent starting place.

### CODE REVIEW

**Comment by thereisnogabe** [comment]
friendly bump @msporny @BigBlueHat

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
> friendly bump @msporny @BigBlueHat

Thanks for the bump @decentralgabe, I missed the original PR request.

**Comment by msporny** [comment]
Hrm, this PR seems to have broken all the fixes we've done in the past few weeks... I'm going to restore the branch to figure out what went wrong...

Yeah, this PR deletes features added over the past two weeks:

https://github.com/w3c/respec-vc/pull/28/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L11-L18

https://github.com/w3c/respec-vc/pull/28/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L31-L37

https://github.com/w3c/respec-vc/pull/28/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L65-L188

Looks like it was based on an old copy of `main` that needed to be updated, and this PR rebased on top of it. Sorry that I didn't catch this before merging. 

@decentralgabe, can you please look at what went wrong and rebase this branch and open a new PR that doesn't delete the tab rename and autohash generation feature set?

**Comment by msporny** [comment]
> @decentralgabe, can you please look at what went wrong and rebase this branch and open a new PR that doesn't delete the tab rename and autohash generation feature set?

I tried rebasing and fixing merges for two hours and couldn't fix the new babel-induced errors. I have little understanding of all the code being pulled in, and am now out of time to try and debug further. /cc @BigBlueHat and @tminard in case they might have an easier time doing a rebase with this code base w/o removing the tab renaming and autohash code.

**Pull request merged**
